services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dbnet

  proxysql:
    image: proxysql/proxysql
    container_name: proxysql
    restart: always
    ports:
      - "6032:6032"  # Admin interface
      - "6033:6033"  # MySQL clients connect here
    volumes:
      - ./proxysql.cnf:/etc/proxysql.cnf
    depends_on:
      - mysql
    networks:
      - dbnet

volumes:
  mysql_data:

networks:
  dbnet: